# Docker file for the development environment of the frontend application
# FROM node:20-alpine
# WORKDIR /app

# COPY package.*json ./

# RUN npm install

# COPY . .

# EXPOSE 5000

# CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0" ]


# Docker file for the production environment of the frontend application
FROM node:20-alpine AS build
WORKDIR /app

COPY package.*json ./

RUN npm install

COPY . .

RUN npm run build

# production stage

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]


